apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: frontend
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: graphtuitous
  name: frontend
  namespace: user1-tenant
spec:
  path: /
  port:
    targetPort: 8080
  to:
    kind: Service
    name: frontend
    weight: null
status: {}
