apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: haproxy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: haproxy
    app.kubernetes.io/part-of: graphtuitous
  name: haproxy
  namespace: user1-tenant
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: haproxy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: haproxy
    spec:
      containers:
      - image: quay.io/jduimovich0/haproxy@sha256:2ecd181044778392a83325897ec38750970dbe981bc744884b1ea0a3431b88f4
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 128Mi
status: {}
