apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: haproxy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: haproxy
    app.kubernetes.io/part-of: graphtuitous
  name: haproxy
  namespace: user1-tenant
spec:
  path: /
  port:
    targetPort: 8080
  to:
    kind: Service
    name: haproxy
    weight: null
status: {}
