apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fib-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fib-go
    app.kubernetes.io/part-of: graphtuitous
  name: fib-go
  namespace: user1-tenant
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: fib-go
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: fib-go
    spec:
      containers:
      - image: quay.io/jduimovich0/fib-go@sha256:fab481e46e2485b67d4ec4859dbf8fb479826513c9605180a5cadb1917a3b83f
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 64Mi
status: {}
